POST http://localhost:9090/projects/milestones/1
Content-Type: application/json

{
  "stepName": "test",
  "startDate": "2024-02-22 11:11:11",
  "endDate": "2024-03-29 11:11:11"
}

### 존재하지 않는 프로젝트 아이디를 넣었을 때

POST http://localhost:9090/projects/milestones/100
Content-Type: application/json

{
  "stepName": "test",
  "startDate": "2024-02-22 11:11:11",
  "endDate": "2024-03-29 11:11:11"
}

###

PUT http://localhost:9090/projects/milestones/1/1
Content-Type: application/json

{
  "stepName": "updateTest",
  "startDate": "2024-02-22 11:11:11",
  "endDate": "2024-03-29 11:11:11"
}

### 존재하지 않는 마일스톤 아이디를 넣었을 때

PUT http://localhost:9090/projects/milestones/100/1
Content-Type: application/json

{
  "stepName": "updateTest",
  "startDate": "2024-02-22 11:11:11",
  "endDate": "2024-03-29 11:11:11"
}

### 존재하지 않는 프로젝트 아이디를 넣었을 때

PUT http://localhost:9090/projects/milestones/1/100
Content-Type: application/json

{
  "stepName": "updateTest",
  "startDate": "2024-02-22 11:11:11",
  "endDate": "2024-03-29 11:11:11"
}

###

DELETE http://localhost:9090/projects/milestones/2

### 존재하지 않는 마일스톤을 제거하려 할 때

DELETE http://localhost:9090/projects/milestones/100

###

GET http://localhost:9090/projects/milestones

###

GET http://localhost:9090/projects/milestones/1

### 존재하지 않는 마일스톤 아이디를 넣었을 때

GET http://localhost:9090/projects/milestones/100

###

GET http://localhost:9090/projects/1/milestones