POST http://localhost:9090/projects
Content-Type: application/json

{
  "projectState": "활성",
  "memberId": "test",
  "projectName": "test project"
}

### 존재하지 않는 상태를 넣었을 때

POST http://localhost:9090/projects
Content-Type: application/json

{
  "projectState": "not exist state",
  "memberId": "test",
  "projectName": "test project"
}

###

PUT http://localhost:9090/projects/1/status
Content-Type: application/json

{
  "state": "휴면"
}

### 존재하지 않는 프로젝트 아이디를 넣었을 때

PUT http://localhost:9090/projects/100/status
Content-Type: application/json

{
  "state": "휴면"
}

### 존재하지 않는 상태를 넣었을 때

PUT http://localhost:9090/projects/1/status
Content-Type: application/json

{
  "state": "not exist state"
}

###

POST http://localhost:9090/projects/1/members
Content-Type: application/json

{
  "memberId": "testMember"
}

### 존재하지 않는 프로젝트 아이디를 넣었을 때

POST http://localhost:9090/projects/100/members
Content-Type: application/json

{
  "memberId": "testMember"
}

###

DELETE http://localhost:9090/projects/1/members
Content-Type: application/json

{
  "memberId": "testMember"
}

### 존재하지 않는 프로젝트 아이디를 넣었을 때

DELETE http://localhost:9090/projects/100/members
Content-Type: application/json

{
  "memberId": "testMember"
}

### 관리자를 멤버에서 제거하려 했을 때

DELETE http://localhost:9090/projects/1/members
Content-Type: application/json

{
  "memberId": "test"
}

###

GET http://localhost:9090/projects/testMember/projects

###

GET http://localhost:9090/projects/1/members

###

GET http://localhost:9090/projects/1

### 존재하지 않는 프로젝트 아이디를 주었을 때 예외 처리

GET http://localhost:9090/projects/100